version: '2'

services:
  proxy:
    build: ./src
    command: bash -c "./run.sh"
    volumes: 
        - /var/log/erss:/var/log/erss:rw
    ports:
        - "12345:12345"
    tty: true


# volumes:
#   data-volume: